### ISSUE TITLE
Some issues about the code.

### ISSUE THREAD

**Issue by lindameiguo** [Z-Zheng/FreeNet#2]
I try to run your code on the Pavia data set.

Traceback (most recent call last):
  File "d:/FreeNet-master/train.py", line 63, in <module>
    opts=args.opts)
  File `"D:\software\anaconda\lib\site-packages\simplecv\dp_train.py",` line 44, in run
    traindata_loader = make_dataloader(cfg['data']['train'])
  File "D:\software\anaconda\lib\site-packages\simplecv\data\data_loader.py", line 9, in make_dataloader
    raise ValueError('{} is not support now.'.format(dataloader_type))
ValueError: NewPaviaLoader is not support now.

Looking forward to hearing from you!

**Comment by Z-Zheng** [comment]
This bug has been fixed in last month. Please clone the newest code.

**Comment by lindameiguo** [comment]
Thank you~
